### ISSUE TITLE
训练log情况

### ISSUE THREAD

**Issue by 1707001010** [YaoZhang93/mmFormer#2]
您好，请问训练log什么样才是正常的样子呢？我训练1000轮，loss还是6,7左右，这种是有问题吗？

**Comment by YaoZhang93** [comment]
您好，这种是正常的，loss的值是分割loss和几个辅助loss的累加之和。

**Comment by 1707001010** [comment]
您好，我还有个疑问就是，模型是将Brats2018中 285个样本进行交叉验证吗，请问最终的测试结果是上传比赛后的结果吗，还是作者有其它的实验设置呢

**Comment by YaoZhang93** [comment]
是285个样本交叉验证的，BraTS的线上评测并不支持缺失模态的评测方式
