### ISSUE TITLE
测试指标求助

### ISSUE THREAD

**Issue by chunyuxiaodao** [YaoZhang93/mmFormer#22]
作者你好，向你请教， 在测试代码中得到的'whole', 'core', 'enhancing', 数值是对应论文中的‘WT’，‘TC ’，‘ET’吗？ 那'enhancing_postpro'的含义是什么呢？我并不清楚如何得到论文中的‘WT’，‘TC ’，‘ET’，希望能到您的回复。

**Comment by YaoZhang93** [comment]
是对应的，enhancing_postpro是对ET进行了后处理的结果。

**Comment by chunyuxiaodao** [comment]
谢谢你的解答
