### ISSUE TITLE
train

### ISSUE THREAD

**Issue by lina9905** [YaoZhang93/mmFormer#3]
作者您好，我看您的论文里写的是交叉验证，但是train.py里没有验证，可以给个完整的训练代码吗？

**Comment by YaoZhang93** [comment]
您好，请参考data/BraTS.py中134行split_dataset，将select参数换成需要的fold就可以了

**Comment by lina9905** [comment]
嗯嗯 好的，我还有一个疑问，就是您设置的epoch=1000，然后用最后一个epoch的pth文件进行测试，是怎么保证最后一个epoch的权重文件是最好的。比如说在第800个epoch时已经得到最好的结果了，但是再继续训练的话会不会overfitting

**Comment by YaoZhang93** [comment]
我们并没有专门挑一个最好的epoch，只是从训练曲线上观察loss趋于平缓了。Transformer的capacity挺大的，延长训练时间您可以期待仍会有一些提升。

**Comment by lina9905** [comment]
> 我们并没有专门挑一个最好的epoch，只是从训练曲线上观察loss趋于平缓了。Transformer的capacity挺大的，延长训练时间您可以期待仍会有一些提升。

嗯嗯 谢谢您

**Comment by YaoZhang93** [comment]
您好，我们重新整理了代码，您可以试一试
