### ISSUE TITLE
code

### ISSUE THREAD

**Issue by yunqiang6265** [YaoZhang93/mmFormer#5]
您好，最近看到您的论文，想跑一下实验中的代码，发现代码中有许多注释，由于代码看的不是很懂，不知道您公开的代码中是否对这些注释需要另作处理，期待您的回复，谢谢。
<img width="816" alt="image" src="https://user-images.githubusercontent.com/110715233/183239441-d1665069-a539-40c7-ad31-aed69a1c1726.png">
<img width="827" alt="image" src="https://user-images.githubusercontent.com/110715233/183239540-bead51ba-8470-4ca0-9f71-961a88e523be.png">

**Comment by YaoZhang93** [comment]
您好，感谢您的关注。
注释掉的代码是不需要使用的。

**Comment by YaoZhang93** [comment]
您好，感谢您的关注。
注释掉的代码是不需要使用的。

**Comment by YaoZhang93** [comment]
我们重新整理了代码，去掉了不必要的注释，现有的代码更简洁，您可以试一试
