### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by linda0227** [YaoZhang93/mmFormer#6]
您好，请问这是最终版的代码吗？我看论文里只有dice loss，但是代码里还加了另外一个loss。

**Comment by YaoZhang93** [comment]
是的，这个版本用了dice+CE，整体效果比之前更好一点

**Comment by linda0227** [comment]
> 您好，请问这是最终版的代码吗？我看论文里只有dice loss，但是代码里还加了另外一个loss。

还有论文里是2018的数据集，但是propess.py 处理的是2020的数据集。
