### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Linzy0227** [YaoZhang93/mmFormer#9]
作者您好，可以向您咨询一下一些额外的问题吗，不知道您有没有尝试过将验证集的分割结果上传到在线网站，我用您提到的TransBTS中的代码上传19数据集是没问题的，但是上传20数据集出现Origin mismatch > 100100%' in axis '1'.
Images are not aligned, please ensure both images have the same origin, spacing and direction cosines before trying to extract similarity measures (use '-inf' for image information).
Calculating Stats for Subject BraTS20_Validation_001 Failed，实在找不出问题出在哪里，如果您知道的话，非常感谢您可以帮我解答一下。

**Comment by YaoZhang93** [comment]
您可以看到报错信息是：“please ensure both images have the same origin, spacing and direction cosines”，因此应该是您保存的分割结果的affine信息不对。可以使用以下方式修正分割结果的affine：
affine = nib.load(IMG_PATH)._affine
nib.save(nib.Nifti1Image(seg, affine), SEG_PATH)


 Original Message 
Sender: ***@***.***>
Recipient: ***@***.***>
Cc: ***@***.***>
Date: Tuesday, Dec 13, 2022 22:17
Subject: [YaoZhang93/mmFormer] 数据集问题 (Issue #9)


作者您好，可以向您咨询一下一些额外的问题吗，不知道您有没有尝试过将验证集的分割结果上传到在线网站，我用您提到的TransBTS中的代码上传19数据集是没问题的，但是上传20数据集出现Origin mismatch > 100100%' in axis '1'.
 Images are not aligned, please ensure both images have the same origin, spacing and direction cosines before trying to extract similarity measures (use '-inf' for image information).
 Calculating Stats for Subject BraTS20_Validation_001 Failed，实在找不出问题出在哪里，如果您知道的话，非常感谢您可以帮我解答一下。

**Comment by RENJI118** [comment]
如果想换成BraTS2020数据集呢
